global function ModSettingsTest

void function ModSettingsTest()
{
    AddModTitle("SL TEST")
    AddModCategory( "lessgo" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )
    AddConVarSetting( "dotres_debug_draw_dimensions", "dotres debug", "float3" )

    // AddModSettingsDropDown( "dotres_debug_draw_dimensions", "debug draw dimensions (dotres) - using index", ["Disabled", "Enabled" ], true )
    AddModSettingsColorPicker( "dotres_debug_draw_dimensions", "color picker test" )
    AddModSettingsColorPicker( "dotres_debug_test_color", "color picker test 2" )
}